# A description of the data and how it will be used to solve the problem

- Data Sources
Firstly, I downloaded 'red-light-camera-locations.csv' for exploring where they are located in Chicago. Secondly, 'US_Accident_DATAA.csv' was chosen for exloring which area the car accidents happend in Chicago. I got these two datasets from Kaggle. Since it should be shown on the map, longtitude and latitude are needed in both datasets.

- Data Cleaning
To get needed datas only, I processed data cleaning by SQL.  
In the case of 'red-light-camera-locations.csv', I selected 'longtitute' and 'latitude' only in the dataset. 
In the case of 'US_Accident_DATAA.CSV', I made table filtered by city's name which is 'Chicago'.

In [25]:
import ibm_db

In [26]:
dsn_hostname = "dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net" 
dsn_uid = "rnj04448"       
dsn_pwd = "n5n65dx2lq1^qt7f"

dsn_driver = "{IBM DB2 ODBC DRIVER}"
dsn_database = "BLUDB"        
dsn_port = "50000"          
dsn_protocol = "TCPIP"

In [27]:
dsn = (
    "DRIVER={0};"
    "DATABASE={1};"
    "HOSTNAME={2};"
    "PORT={3};"
    "PROTOCOL={4};"
    "UID={5};"
    "PWD={6};").format(dsn_driver, dsn_database, dsn_hostname, dsn_port, dsn_protocol, dsn_uid, dsn_pwd)
print(dsn)

DRIVER={IBM DB2 ODBC DRIVER};DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=rnj04448;PWD=n5n65dx2lq1^qt7f;

In [28]:
try:
    conn = ibm_db.connect(dsn, "", "")
    print ("Connected to database: ", dsn_database, "as user: ", dsn_uid, "on host: ", dsn_hostname)

except:
    print ("Unable to connect: ", ibm_db.conn_errormsg() )

Connected to database:  BLUDB as user:  rnj04448 on host:  dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net

In [30]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /opt/conda/envs/Python36/lib/python3.6/site-packages (0.4.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (1.2.18)
Requirement already satisfied: six in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (1.12.0)
Requirement already satisfied: sqlparse in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (0.3.1)
Requirement already satisfied: ipython>=1.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (7.2.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prettytable<1 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython-sql) (0.7.2)
Requirement already satisfied: pygments in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (2.3.1)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (2.0.8)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (4.3.2)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (40.8.0)
Requirement already satisfied: jedi>=0.10 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (0.13.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (4.6.0)
Requirement already satisfied: backcall in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: decorator in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (4.3.2)
Requirement already satisfied: pickleshare in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: wcwidth in /opt/conda/envs/Python36/lib/python3.6/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.1.7)
Requirement already satisfied: parso>=0.3.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.3.2)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)

In [31]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [53]:
%sql ibm_db_sa://rnj04448:n5n65dx2lq1%5Eqt7f@dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net:50000/BLUDB

In [80]:
%sql SELECT *  FROM CHICAGO_CAMERA LIMIT 5

 * ibm_db_sa://rnj04448:***@dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net:50000/BLUDB
Done.

[('California-Peterson', 'NB', 'EB', None, '2009-06-29T00:00:00.000', Decimal('41.990442'), Decimal('-87.699401'), '{\'latitude\': \'41.990442\', \'human_address\': \'{"address": "", "city": "", "state": "", "zip": ""}\', \'longitude\': \'-87.699401\'}', 46, 4450, 20, 15, 24),
 ('Central-Addison', 'SB', 'EB', None, '2010-11-15T00:00:00.000', Decimal('41.945877'), Decimal('-87.766754'), '{\'latitude\': \'41.945877\', \'human_address\': \'{"address": "", "city": "", "state": "", "zip": ""}\', \'longitude\': \'-87.766754\'}', 25, 22254, 15, 361, 44),
 ('Western-63rd', 'NB', 'EB', None, '2007-11-12T00:00:00.000', Decimal('41.779214'), Decimal('-87.683638'), '{\'latitude\': \'41.779214\', \'human_address\': \'{"address": "", "city": "", "state": "", "zip": ""}\', \'longitude\': \'-87.683638\'}', 44, 22257, 64, 370, 2),
 ('Halsted-79th', 'NB', 'EB', None, '2008-04-30T00:00:00.000', Decimal('41.750643'), Decimal('-87.644043'), '{\'latitude\': \'41.750643\', \'human_address\': \'{"address": "", "city": "", "state": "", "zip": ""}\', \'longitude\': \'-87.644043\'}', 17, 21554, 70, 556, 31),
 ('Wacker-Lake', 'NB', 'SB', None, '2018-02-19T00:00:00.000', Decimal('41.885700'), Decimal('-87.637000'), '{\'latitude\': \'41.8857\', \'human_address\': \'{"address": "", "city": "", "state": "", "zip": ""}\', \'longitude\': \'-87.637\'}', 22, 14914, 38, 92, 36)]

In [82]:
%sql SELECT latitude, longitude  FROM CHICAGO_CAMERA LIMIT 5

 * ibm_db_sa://rnj04448:***@dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net:50000/BLUDB
Done.

[(Decimal('41.990442'), Decimal('-87.699401')),
 (Decimal('41.945877'), Decimal('-87.766754')),
 (Decimal('41.779214'), Decimal('-87.683638')),
 (Decimal('41.750643'), Decimal('-87.644043')),
 (Decimal('41.885700'), Decimal('-87.637000'))]

In [81]:
%sql SELECT *  FROM US_ACCIDENT_DATAA LIMIT 5

 * ibm_db_sa://rnj04448:***@dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net:50000/BLUDB
Done.

[('A-745607', 'MapQuest', 241, 2, 43825, Decimal('43825.85469'), Decimal('31.588751'), Decimal('-85.278580'), 'Lane blocked due to accident on US-431 both ways before AL-10.', None, 'US Highway 431 N', 'R', 'Abbeville', 'Henry', 'AL', '36310', 'US', 'US/Central', 'KDHN', Decimal('43825.82847'), 62, 62, 80, Decimal('29.76'), Decimal('10.00'), 'ENE', 3, Decimal('0.00'), 'Fair', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Night', 'Night', 'Night', 'Night'),
 ('A-746720', 'MapQuest', 201, 2, 43826, Decimal('43826.33712'), Decimal('34.184361'), Decimal('-82.374840'), 'Accident on Lucy Ln near Garlington Ln.', 309, 'Garlington St', 'R', 'Abbeville', 'Abbeville', 'SC', '29620-2810', 'US', 'US/Eastern', 'KGRD', Decimal('43826.28889'), 44, 44, 96, Decimal('29.61'), Decimal('10.00'), 'CALM', 0, Decimal('0.00'), 'Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Night', 'Night', 'Day', 'Day'),
 ('A-759981', 'MapQuest', 201, 2, 43803, Decimal('43803.43427'), Decimal('34.187969'), Decimal('-82.399742'), 'Accident on SC-71 at SC-28-CONN.', 1502, 'N Main St', 'R', 'Abbeville', 'Abbeville', 'SC', '29620-6502', 'US', 'US/Eastern', 'KGRD', Decimal('43803.37222'), 39, 33, 70, Decimal('29.17'), Decimal('10.00'), 'WSW', 8, Decimal('0.00'), 'Fair', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Day', 'Day', 'Day', 'Day'),
 ('A-762601', 'MapQuest', 201, 2, 43804, Decimal('43804.37685'), Decimal('34.184212'), Decimal('-82.320541'), 'Accident on SC-72 at Durham Rd.', None, 'Durham Rd', 'R', 'Abbeville', 'Abbeville', 'SC', '29620', 'US', 'US/Eastern', 'KGRD', Decimal('43804.33056'), 36, 31, 79, Decimal('29.38'), Decimal('10.00'), 'WSW', 6, Decimal('0.00'), 'Fair', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Day', 'Day', 'Day', 'Day'),
 ('A-769718', 'MapQuest', 201, 2, 43808, Decimal('43808.49645'), Decimal('34.103802'), Decimal('-82.338943'), 'Accident on Cedar Springs St at Parsons Mountain Rd.', 3501, 'Cedar Spgs S', 'R', 'Abbeville', 'Abbeville', 'SC', '29620-6320', 'US', 'US/Eastern', 'KGRD', Decimal('43808.45556'), 45, 45, 76, Decimal('29.44'), Decimal('10.00'), 'N', 3, Decimal('0.00'), 'Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Day', 'Day', 'Day', 'Day')]

In [83]:
%sql SELECT *  FROM US_ACCIDENT_DATAA WHERE city_name = 'Chicago' LIMIT 5

 * ibm_db_sa://rnj04448:***@dashdb-txn-sbox-yp-dal09-08.services.dal.bluemix.net:50000/BLUDB
Done.

[('A-745684', 'MapQuest', 201, 2, 43825, Decimal('43825.60616'), Decimal('42.011959'), Decimal('-87.777527'), 'Accident on Touhy Ave both ways at Meade Ave.', 5993, 'W Touhy Ave', 'L', 'Chicago', 'Cook', 'IL', '60646-1263', 'US', 'US/Central', 'KORD', Decimal('43825.57708'), 61, 61, 64, Decimal('29.19'), Decimal('10.00'), 'WSW', 13, Decimal('0.00'), 'Mostly Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Day', 'Day', 'Day', 'Day'),
 ('A-747021', 'MapQuest', 201, 2, 43826, Decimal('43826.28454'), Decimal('41.776642'), Decimal('-87.613129'), 'Accident on 65th St at Eberhart Ave.', 6500, 'S Eberhart Ave', 'R', 'Chicago', 'Cook', 'IL', '60637-3206', 'US', 'US/Central', 'KMDW', Decimal('43826.16181'), 37, 28, 79, Decimal('29.48'), Decimal('8.00'), 'W', 14, Decimal('0.00'), 'Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Night', 'Night', 'Night', 'Night'),
 ('A-747022', 'MapQuest', 201, 2, 43826, Decimal('43826.23277'), Decimal('41.693432'), Decimal('-87.627922'), 'Accident on 110th Pl at Wentworth Ave.', 198, 'W 110th Pl', 'R', 'Chicago', 'Cook', 'IL', '60628-4211', 'US', 'US/Central', 'KMDW', Decimal('43826.20347'), 37, 30, 79, Decimal('29.49'), Decimal('8.00'), 'W', 9, Decimal('0.00'), 'Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Night', 'Night', 'Night', 'Night'),
 ('A-747030', 'MapQuest', 201, 2, 43826, Decimal('43826.31439'), Decimal('41.874062'), Decimal('-87.674858'), 'Accident on Ogden Ave at Harrison St.', None, 'W Ogden Ave', 'R', 'Chicago', 'Cook', 'IL', '60612', 'US', 'US/Central', 'KMDW', Decimal('43826.28681'), 35, 25, 82, Decimal('29.55'), Decimal('7.00'), 'W', 16, Decimal('0.00'), 'Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'Night', 'Day', 'Day', 'Day'),
 ('A-747048', 'MapQuest', 201, 2, 43826, Decimal('43826.79601'), Decimal('42.008549'), Decimal('-87.785759'), 'Accident on US-14 Caldwell Ave at Lexington Ln.', 7051, 'N Caldwell Ave', 'R', 'Chicago', 'Cook', 'IL', '60646-1011', 'US', 'US/Central', 'KORD', Decimal('43826.78542'), 32, 32, 82, Decimal('29.52'), Decimal('9.00'), 'SSW', 3, Decimal('0.00'), 'Partly Cloudy', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'Night', 'Night', 'Night', 'Night')]